Repository craftcms/docs, pull requests merged in 2021-11, with the labels that each got.

#265 Fix 404ing Link
  docs/commerce/3.x/addresses.md
Labels: 🐞 bug

#267 Add Templating Example for Order Histories
  docs/commerce/3.x/custom-order-statuses.md
Labels: 📖 commerce, enhancement

#269 Fix typo in graphql documentation
  docs/3.x/extend/graphql.md
Labels: 🐞 bug, 📖 cms
