Repository craftcms/docs, pull requests merged in 2021-08, with the labels that each got.

#244 Adds detail about Site Groups & Propagation Method
  docs/3.x/sites.md
Labels: 📖 cms

#245 Added Craft Autocomplete package as a tip
  docs/3.x/extend/coding-guidelines.md
Labels: enhancement

#248 Update graphql.md
  docs/3.x/extend/graphql.md
Labels: 🐞 bug

#246 Update updating.md
  docs/nitro/2.x/updating.md
Labels: 🐞 bug
